export { default as AccordionPage } from './AccordionPage'
export { default as ColorPicker } from './ColorPicker'
export { default as ImageSearch } from './ImageSearch'
export { default as SliderAndRating } from './SliderAndRating'
export { default as Hero } from '../pages/Hero'